### ISSUE TITLE
'Reviewer' object has no attribute 'unfocus_typing_box'

### ISSUE THREAD

**Issue by hedgss** [r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1#11]
Anki works properly, but it just shows the following exception in a separate window: 
`Caught exception: Traceback (most recent call last):   File "aqt.webview", line 562, in handler   File "C:\Users\H\AppData\Roaming\Anki2\addons21\711285688\Multiple_type_fields_on_card_for_2_1.py", line 131, in myOnTypedAnswer     self.unfocus_typing_box() AttributeError: 'Reviewer' object has no attribute 'unfocus_typing_box' 
`

Debug Info:
Anki 2.1.56 (07fd88dd) 
Python 3.9.15 Qt 6.4.0 PyQt 6.4.0 
Platform: Windows-10-10.0.22621 
Flags: frz=True ao=True sv=2
 Add-ons, last update check: 2023-01-16 03:05:08

<img width="967" alt="2023-01-16 03_19_43-Card Types for Unregelmäßige Verben" src="https://user-images.githubusercontent.com/8041712/212584721-add3eaee-d1ec-45c0-bceb-d1c90efe7aee.png">

**Comment by unit-of-inductance** [comment]
This seems to be new with 2.1.56, should be fixed now. Sorry for the wait.
