### ISSUE TITLE
Diffs on incorrectly typed answer are backwards.

### ISSUE THREAD

**Issue by Daedalus359** [r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1#13]
The following error only occurs while I have the "Multiple type fields on card for 2.1" add-on enabled, and it occurs with the latest version of Anki for both the QT5 and QT6 versions. Until I upgraded earlier today, I was running a previous version of QT5 Anki with the older UI.

On the following review screen, the correct answers are はな, はなし, and わ. I typed はなしし and わわ for the second and third answers. On the back side of the card, I get the following:

![image](https://github.com/r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1/assets/3870494/d9921738-1632-4e58-8de0-0fec53435403)

Note that the diffs are backwards. Disabling this add-on fixes the bug. Here is a screenshot from a card with just one cloze field while the add-on is disabled. I followed the same pattern above by adding an extra character to the correct answer (although this is not required for the bug to occur). It shows the correct diff behavior:

![image](https://github.com/r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1/assets/3870494/59917241-0658-4e4a-84ef-a3b3825d23dc)

I had a similar issue a few months ago with the QT6 version, but switching to QT5 solved the problem back then. In the current update, the QT5 UI to looks like the QT6 one, so I'm wondering if whatever update added the new UI code also introduced some API changes that this add-on does not handle correctly.

Anki debug info:

```
Anki 2.1.63 (f356f177) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
    Platform: Windows-10-10.0.19045
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-05-16 11:21:57
```

    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Multiple type fields on card for 21 ['711285688', 2023-01-23T08:56, 'None', '']
    Straight Reward ['957961234', 2022-12-12T05:49, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    711285688 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AJT Japanese ['1344485230', 2023-05-09T12:03, 'None', '']
    AnkiConnect ['2055492159', 2023-04-11T10:20, 'None', '']
    Japanese Support ['3918629684', 2022-03-13T20:32, 'None', mod]
    Symbols As You Type ['2040501954', 2022-06-07T21:09, 'None', '']

**Comment by unit-of-inductance** [comment]
Thank you for the report, should be fixed with the newest update. Please reopen this issue if it's not fixed for you
