### ISSUE TITLE
Multiple-type-fields-on-Card-for Anki 2.1  no funciona

### ISSUE THREAD

**Issue by bl0ckh0le** [r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1#7]
instale pero en anki no se encuentra la opcion para hacer mi tarjeta que debo hacer

**Comment by unit-of-inductance** [comment]
You can make a card just as usual in Anki, just that with this Addon it is now possible to add multiple {{type:}} fields. You could e.g. start with the Template from the [addon page](https://ankiweb.net/shared/info/711285688). I'll close this for now, feel free to reopen if you have any further questions.
