### ISSUE TITLE
Not compatible with Anki 2.1.55

### ISSUE THREAD

**Issue by longqinsi** [r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1#8]
Because aqt.reviewer.Reviewer doesn‘t contain the "correct" method any longer in the currently developing version 2.1.55.

**Comment by unit-of-inductance** [comment]
Thank you very much for the information, I have updated the description to mention the incompatibility, and am looking for a fix at the moment.

**Comment by unit-of-inductance** [comment]
This should be fixed with the [latest commits](https://github.com/r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1/commit/3db0a889d31f148f69d38d02934585b88794dc34) and the update to the ankiweb.net page.
